Simplified Windows build fix + some modernization of CMakeBuild files
dnwrnr/sgp4 pull request #16
Opened 2019-06-26 08:54 UTC by pxntus

Windows build fixes:

- GCC compile flags only for Linux/GCC
- Windows related install fix
- No linking against librt since not needed (and unavailable for Windows)
- Including algorithm header to get min (for integers)

CMake modernization:

- Enabling C++11 according to best practices
- Target based approach for include directories of library

2019-07-21 13:54 UTC, dnwrnr requested changes

2019-07-21 13:54 UTC, dnwrnr commented on CMakeLists.txt
> +if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
What about CLANG?

2019-07-21 13:54 UTC, dnwrnr commented on libsgp4/CMakeLists.txt
> +    RUNTIME DESTINATION lib)
Can you explain why the library requires the runtime location specified?

2019-12-07 11:49 UTC, dnwrnr requested changes

2019-12-07 12:51 UTC, pxntus commented on CMakeLists.txt
> +if(CMAKE_COMPILER_IS_GNUCC)
Sorry, I forgot about this. I will try to motivate the change request in the following days. (Just to mention: I actually use my branch of your code in a ground segment tool for satellites that will launch during 2020.)

2020-02-24 12:54 UTC, SpaceIm commented
@pxntus @dnwrnr You could also use CMake feature WINDOWS_EXPORT_ALL_SYMBOLS. Indeed currently a shared libsgp4 fails to link into an executable or shared lib because symbols are not exported on windows.

2026-07-26 21:59 UTC, dnwrnr commented
I have updated the cmake config

2026-07-26 21:59 UTC, closed without merging