Install static library
dnwrnr/sgp4 pull request #37
Opened 2023-11-10 16:32 UTC by srcejon

Currently the static library that is built doesn't get installed. This PR installs it.

2026-07-09 07:27 UTC, jeaogom requested changes

2026-07-09 07:27 UTC, jeaogom commented on libsgp4/CMakeLists.txt
> +install( TARGETS sgp4 LIBRARY DESTINATION lib )
The ARCHIVE type is for static libraries:
```suggestion
install( TARGETS sgp4 ARCHIVE DESTINATION lib )
```
https://cmake.org/cmake/help/v3.13/command/install.html#installing-targets

2026-07-26 21:59 UTC, dnwrnr commented
static lib should be installed

2026-07-27 07:19 UTC, jeaogom commented
Thanks for the response @dnwrnr :)

> static lib should be installed

How/where is this done?

AFAICT `install()` is only used on `sgp4s` (the shared lib).

2026-07-27 07:59 UTC, jeaogom commented
> static lib should be installed

Oh I missed the recent changes in https://github.com/dnwrnr/sgp4/commit/07e3cabc966b43b4cac66686cf36d742f405fdf0.

You are right, it looks like it should be installed now :)

2026-07-27 12:33 UTC, closed without merging